### ISSUE TITLE
Can't access to PDB files

### ISSUE THREAD

**Issue by GerkinDev** [ofpinewood/http-exceptions#102]
Hi,

I'm encountering an issue I'm trying to debug from your package, but I can't load the pdb files of your code, thus I can't set breakpoints.
By inspecting the nupkg, it seems that pdb files aren't included in the nuget at all. Would it be possible to add them in the next release ?

**Comment by petervandenhout** [comment]
Hi @GerkinDev 

I've created symbol packages for the code. And a new release [4.0.2](https://www.nuget.org/packages/Opw.HttpExceptions.AspNetCore/4.0.2). 
I think that this will let you debug the code, but please let me know if not...

> [symbol packages (.snupkg)](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages-snupkg)
