### ISSUE TITLE
InvalidModelException logged as error

### ISSUE THREAD

**Issue by adamjez** [ofpinewood/http-exceptions#44]
*HttpExceptions* package throws `InvalidModelException` exception in case of invalid model state response.
This exception is then catched inside `HttpExceptionsMiddleware` and **logged as error**.

IMO this should **not** be logged as error because invalid model state mostly means that a client request is a malformed. In my use case, we try to solve every error logged but we can't fix client errors.

There should at least exist some configuration to alter this behavior, eg.:
* make logging configurable [HttpExceptionsMiddlware](https://github.com/ofpinewood/http-exceptions/blob/master/src/Opw.HttpExceptions.AspNetCore/HttpExceptionsMiddleware.cs#L68) (as you suggest in comment :))
* don't throw `InvalidModelException`

Is there any possible solution which I missed? What do you think?

**Comment by petervandenhout** [comment]
I will make the logging of errors configurable in the `HttpExceptionsOptions`, like the `IncludeExceptionDetails` and `IsExceptionResponse`. You can then either disable all logging or configure what exceptions you want to have logged.

**Comment by petervandenhout** [comment]
You can now configure if exceptions should be logged by the HttpExceptions middleware or not, default behavior is to log all exceptions (all status codes).

``` csharp
mvcBuilder.AddHttpExceptions(options =>
{
    // Only log the when it has a status code of 500 or higher, or when it not is a HttpException.
    options.ShouldLogException = exception => {
        if ((exception is HttpExceptionBase httpException && (int)httpException.StatusCode >= 500) || !(exception is HttpExceptionBase))
            return true;
        return false;
    };
});
```

**Comment by petervandenhout** [comment]
@adamjez I hope this is a good solution for the problem you had, if not then let me know :)
Version 2.5.0 of the nuget package has been created (https://www.nuget.org/packages/Opw.HttpExceptions.AspNetCore/).
