### ISSUE TITLE
Using RFC as ProblemDetails type

### ISSUE THREAD

**Issue by daniel-white** [ofpinewood/http-exceptions#47]
Would it make sense to have an option for the `ProblemDetails` `Type` Property use the `HelpLink` text from the defined `Exception`s that have a reference to a HTTP status code in an RFC? 

Meaning - why not map to these?

https://github.com/ofpinewood/http-exceptions/blob/master/src/Opw.HttpExceptions/ResponseStatusCodeLink.cs

**Comment by petervandenhout** [comment]
I think that would actually make sense yes. 

I'll update the `ProblemDetailsExceptionMapper` to return the `Exception.HelpLink` or an URI with the Exception type name ("error:[Type:slug]"). And update the `ProblemDetailsHttpResponseMapper` to return a status code information link (https://tools.ietf.org/html/rfc7231) or the URI with the HTTP status name ("error:[status:slug]").

**Comment by petervandenhout** [comment]
@daniel-white I've created a PR for the change, let me know if this work for you or if it needs something more.
https://github.com/ofpinewood/http-exceptions/pull/48

**Comment by daniel-white** [comment]
@petervandenhout Yeah that’s what I was thinking. However it introduces a slight breaking change. Might be good to put it behind a setting flag.

**Comment by petervandenhout** [comment]
@daniel-white 
I've updated it to make using a help link for ProblemDetails type property configurable in the options.
When UseHelpLinkAsProblemDetailsType is set to true the mappers uses the Exception.HelpLink or the HTTP status code information link to map the ProblemDetails.Type property. And when you want to set a default link for your help pages, you can set DefaultHelpLinkForProblemDetailsType.

mvcBuilder.AddHttpExceptions(options =>
{
    options.UseHelpLinkAsProblemDetailsType = true;
    options.DefaultHelpLink = new Uri("http://www.example.com/help-page");
});

**Comment by daniel-white** [comment]
@petervandenhout This is great. Thanks!

**Comment by petervandenhout** [comment]
The changes have been merged and a new release has been created (2.7). It will be available on nuget soon.

https://www.nuget.org/packages/Opw.HttpExceptions.AspNetCore/

**Comment by petervandenhout** [comment]
The changes have been merged and a new release has been created (2.7). It will be available on nuget soon.

https://www.nuget.org/packages/Opw.HttpExceptions.AspNetCore/
