### ISSUE TITLE
Generated JSON ValidationProblemDetails response not honoring AddNewtonsoftJson and AddJsonOptions for PascalCase; produces camelCase instead

### ISSUE THREAD

**Issue by GStoynev** [ofpinewood/http-exceptions#76]
Having this configuration in a .net core 3.1 web api ([ApiController]) controller generates all lower-case JSON when a ValidationErrorException is thrown:
`services.AddControllers(c => { c.Filters.Add<AsAuthenticationFilter>(); })

                //tried that, too .AddJsonOptions(options => { options.JsonSerializerOptions.PropertyNamingPolicy = null; })
                .AddNewtonsoftJson(
                    options =>
                    {
                        // Use the default property (Pascal) casing
                        options.SerializerSettings.ContractResolver = new DefaultContractResolver();
                    })
                .AddHttpExceptions(
                    options =>
                    {
                        options.IsExceptionResponse = context => context.Response.StatusCode >= 500;
                    });`

produces (actual result):
`{"type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","title":"ValidationError","status":400,"detail":"Exception of type 'Opw.HttpExceptions.ValidationErrorException'1[System.String]' was thrown.","instance":"/api/MyController/MyAction","errors":{"User-entered contract number":["112233sdf does not exist"]}}`

should produce (expected result):
``{"Type":"https://tools.ietf.org/html/rfc7231#section-6.5.1","Title":"ValidationError","Status":400,"Detail":"Exception of type 'Opw.HttpExceptions.ValidationErrorException'1[System.String]' was thrown.","Instance":"/api/MyController/MyAction","Errors":{"User-entered contract number":["112233sdf does not exist"]}}``

The "happy path" of same controller action as well as all other controllers and actions produce PascalCase JSON results.

**Comment by petervandenhout** [comment]
@GStoynev the `ProblemDetails` are following the [rfc7807 - Problem Details for HTTP APIs](https://tools.ietf.org/html/rfc7807) standard. That standard defines the exact property names, making them `PascalCase` would violate the standard. That is why it will always output the `ProblemDetails` in `camelCase`.

The frameworks `ProblemDetailsJsonConverter` also enforces this: https://github.com/dotnet/aspnetcore/blob/c925f99cddac0df90ed0bc4a07ecda6b054a0b02/src/Mvc/Mvc.Core/src/Infrastructure/ProblemDetailsJsonConverter.cs
